package cli

import (
	"errors"
	"fmt"
	"io"
	"log/slog"
	"strings"

	"helm-release-size-analyser/internal/analyse"
	"helm-release-size-analyser/internal/config"
	"helm-release-size-analyser/internal/helminstall"
	"helm-release-size-analyser/internal/report"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

type PolicyError struct {
	Status analyse.Status
}

func (e *PolicyError) Error() string {
	return fmt.Sprintf("release size policy failed with status %s", e.Status)
}

func ExitCode(err error) int {
	if _, ok := errors.AsType[*PolicyError](err); ok {
		return 2
	}
	return 1
}

func NewRootCommand(stdout, stderr io.Writer) *cobra.Command {
	v := viper.New()
	var configFile string

	root := &cobra.Command{
		Use:           "helm-release-size-analyser",
		Short:         "Analyse the size of the Secret generated by a Helm release",
		SilenceErrors: true,
		SilenceUsage:  true,
	}
	root.SetOut(stdout)
	root.SetErr(stderr)
	root.PersistentFlags().StringVar(&configFile, "config", "", "configuration file")
	root.PersistentFlags().String("log-level", "info", "log level: debug, info, warn, error")
	root.PersistentFlags().String("log-format", "text", "log format: text or json")

	analyseCmd := &cobra.Command{
		Use:   "analyse CHART",
		Short: "Install a chart in memory and analyse its Helm release Secret",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := loadConfig(v, cmd, configFile)
			if err != nil {
				return err
			}
			logger := newLogger(stderr, cfg.LogLevel, cfg.LogFormat)
			logger.Debug("starting analysis", slog.String("chart", args[0]))

			installed, err := helminstall.Install(cmd.Context(), args[0], cfg, logger)
			if err != nil {
				return err
			}
			result, err := analyse.Build(installed, cfg.LimitBytes)
			if err != nil {
				return err
			}
			if err := report.Write(stdout, cfg.Output, result); err != nil {
				return fmt.Errorf("write report: %w", err)
			}
			if policyFails(cfg.FailOn, result.Status) {
				return &PolicyError{Status: result.Status}
			}
			return nil
		},
	}
	flags := analyseCmd.Flags()
	flags.String("release-name", "", "release name (defaults to chart name)")
	flags.String("namespace", "default", "simulated release namespace")
	flags.StringSliceP("values", "f", nil, "values file (repeatable)")
	flags.StringArray("set", nil, "set a value")
	flags.StringArray("set-string", nil, "set a string value")
	flags.StringArray("set-file", nil, "set a value from a file")
	flags.Bool("include-crds", false, "include CRDs in the stored manifest")
	flags.Int("limit-bytes", config.DefaultLimitBytes, "Secret data size policy limit")
	flags.String("fail-on", "never", "policy failure level: never, warning, error")
	flags.StringP("output", "o", "table", "output format: table, json, yaml")

	root.AddCommand(analyseCmd)
	return root
}

func loadConfig(v *viper.Viper, cmd *cobra.Command, configFile string) (config.Config, error) {
	v.SetEnvPrefix("HELM_RELEASE_SIZE_ANALYSER")
	v.SetEnvKeyReplacer(strings.NewReplacer("-", "_", ".", "_"))
	v.AutomaticEnv()

	if err := v.BindPFlags(cmd.Flags()); err != nil {
		return config.Config{}, fmt.Errorf("bind command flags: %w", err)
	}
	if err := v.BindPFlags(cmd.Root().PersistentFlags()); err != nil {
		return config.Config{}, fmt.Errorf("bind global flags: %w", err)
	}
	if configFile != "" {
		v.SetConfigFile(configFile)
		if err := v.ReadInConfig(); err != nil {
			return config.Config{}, fmt.Errorf("read config file: %w", err)
		}
	}

	var cfg config.Config
	if err := v.Unmarshal(&cfg); err != nil {
		return config.Config{}, fmt.Errorf("decode configuration: %w", err)
	}
	if err := cfg.Validate(); err != nil {
		return config.Config{}, fmt.Errorf("invalid configuration: %w", err)
	}
	return cfg, nil
}

func newLogger(out io.Writer, level, format string) *slog.Logger {
	var slogLevel slog.Level
	switch level {
	case "debug":
		slogLevel = slog.LevelDebug
	case "warn":
		slogLevel = slog.LevelWarn
	case "error":
		slogLevel = slog.LevelError
	default:
		slogLevel = slog.LevelInfo
	}
	options := &slog.HandlerOptions{Level: slogLevel}
	if format == "json" {
		return slog.New(slog.NewJSONHandler(out, options))
	}
	return slog.New(slog.NewTextHandler(out, options))
}

func policyFails(failOn string, status analyse.Status) bool {
	switch failOn {
	case "warning":
		return status == analyse.StatusWarning || status == analyse.StatusError
	case "error":
		return status == analyse.StatusError
	default:
		return false
	}
}
